import { BookingStatus, UserStatus } from '../../../generated/prisma/enums.js';
import { createAuditLog } from '../../../helpers/auditLog.js';
import prisma from '../../../lib/prisma.js';
import AppError from '../../errors/AppError.js';

type Context = { ipAddress?: string; userAgent?: string };
const pageData = <T>(data: T[], total: number, page: number, limit: number) => ({ meta: { page, limit, total, totalPages: Math.ceil(total / limit) }, data });
const publicSelect = { id: true, rating: true, comment: true, createdAt: true, customer: { select: { id: true, name: true } } } as const;
const ownSelect = { ...publicSelect, service: { select: { id: true, title: true } }, bookingId: true, updatedAt: true } as const;
const adminSelect = { ...ownSelect, customerId: true, serviceId: true, deletedAt: true, booking: { select: { providerId: true } } } as const;

export const createReview = async (customerId: string, payload: { bookingId: string; rating: number; comment?: string }, context: Context) => {
  try { return await prisma.$transaction(async (tx) => {
    const booking = await tx.booking.findFirst({ where: { id: payload.bookingId, customerId, status: BookingStatus.COMPLETED, customer: { status: UserStatus.ACTIVE, deletedAt: null } }, select: { id: true, serviceId: true } });
    if (!booking) throw new AppError(404, 'Completed booking not found');
    const review = await tx.review.create({ data: { bookingId: booking.id, customerId, serviceId: booking.serviceId, rating: payload.rating, comment: payload.comment }, select: ownSelect });
    await createAuditLog(tx, { userId: customerId, action: 'REVIEW_CREATED', entityType: 'Review', entityId: review.id, newData: { bookingId: review.bookingId, rating: review.rating }, ...context });
    return review;
  }); } catch (error) { if (typeof error === 'object' && error !== null && 'code' in error && error.code === 'P2002') throw new AppError(409, 'A review already exists for this booking'); throw error; }
};
export const listMyReviews = async (customerId: string, query: { page: number; limit: number; rating?: number; sortOrder: 'asc' | 'desc' }) => { const where = { customerId, deletedAt: null, ...(query.rating ? { rating: query.rating } : {}) }; const [total, data] = await prisma.$transaction([prisma.review.count({ where }), prisma.review.findMany({ where, select: ownSelect, orderBy: { createdAt: query.sortOrder }, skip: (query.page - 1) * query.limit, take: query.limit })]); return pageData(data, total, query.page, query.limit); };
export const listPublicReviews = async (where: { serviceId?: string; providerId?: string }, query: { page: number; limit: number; rating?: number; sortOrder: 'asc' | 'desc' }) => { const filter = { deletedAt: null, ...(where.serviceId ? { serviceId: where.serviceId } : {}), ...(where.providerId ? { booking: { providerId: where.providerId } } : {}), ...(query.rating ? { rating: query.rating } : {}) }; const [total, data] = await prisma.$transaction([prisma.review.count({ where: filter }), prisma.review.findMany({ where: filter, select: publicSelect, orderBy: { createdAt: query.sortOrder }, skip: (query.page - 1) * query.limit, take: query.limit })]); return pageData(data, total, query.page, query.limit); };
export const ratingSummary = async (where: { serviceId?: string; providerId?: string }) => { const result = await prisma.review.aggregate({ where: { deletedAt: null, ...(where.serviceId ? { serviceId: where.serviceId } : {}), ...(where.providerId ? { booking: { providerId: where.providerId } } : {}) }, _avg: { rating: true }, _count: { id: true } }); return { averageRating: result._avg.rating ? Number(result._avg.rating.toFixed(2)) : 0, reviewCount: result._count.id }; };
export const updateReview = async (customerId: string, id: string, payload: { rating?: number; comment?: string | null }, context: Context) => { const review = await prisma.review.findFirst({ where: { id, customerId, deletedAt: null }, select: { id: true, rating: true, comment: true } }); if (!review) throw new AppError(404, 'Review not found'); return prisma.$transaction(async (tx) => { const updated = await tx.review.update({ where: { id }, data: payload, select: ownSelect }); await createAuditLog(tx, { userId: customerId, action: 'REVIEW_UPDATED', entityType: 'Review', entityId: id, oldData: { rating: review.rating, comment: review.comment ?? undefined }, newData: { rating: updated.rating, comment: updated.comment ?? undefined }, ...context }); return updated; }); };
export const softDeleteReview = async (actorId: string, id: string, admin: boolean, context: Context) => { const review = await prisma.review.findFirst({ where: { id, deletedAt: null, ...(admin ? {} : { customerId: actorId }) }, select: { id: true, rating: true } }); if (!review) throw new AppError(404, 'Review not found'); await prisma.$transaction(async (tx) => { await tx.review.update({ where: { id }, data: { deletedAt: new Date() } }); await createAuditLog(tx, { userId: actorId, action: admin ? 'REVIEW_ADMIN_DELETED' : 'REVIEW_DELETED', entityType: 'Review', entityId: id, oldData: { rating: review.rating }, newData: { deleted: true }, ...context }); }); };
export const listAdminReviews = async (query: { page: number; limit: number; rating?: number; sortOrder: 'asc' | 'desc'; customerId?: string; providerId?: string; serviceId?: string; search?: string }) => { const where = { ...(query.rating ? { rating: query.rating } : {}), ...(query.customerId ? { customerId: query.customerId } : {}), ...(query.serviceId ? { serviceId: query.serviceId } : {}), ...(query.providerId ? { booking: { providerId: query.providerId } } : {}), ...(query.search ? { comment: { contains: query.search, mode: 'insensitive' as const } } : {}) }; const [total, data] = await prisma.$transaction([prisma.review.count({ where }), prisma.review.findMany({ where, select: adminSelect, orderBy: { createdAt: query.sortOrder }, skip: (query.page - 1) * query.limit, take: query.limit })]); return pageData(data, total, query.page, query.limit); };
